# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Chain brand name, e.g. Crunchies, Kilimanjaro",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "headquarters_city",
                    models.CharField(
                        help_text="Primary administrative city for chain headquarters",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Restaurant Chain",
                "verbose_name_plural": "Restaurant Chains",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Branch name, e.g. Enugu Ogui Road, Awka Aroma",
                        max_length=150,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("ENUGU", "Enugu"),
                            ("AWKA", "Awka"),
                            ("OWERRI", "Owerri"),
                            ("ABAKALIKI", "Abakaliki"),
                            ("UMUAHIA", "Umuahia"),
                            ("ONITSHA", "Onitsha"),
                            ("ABA", "Aba"),
                        ],
                        help_text="South-East Nigerian operational city",
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENUGU", "Enugu"),
                            ("ANAMBRA", "Anambra"),
                            ("IMO", "Imo"),
                            ("EBONYI", "Ebonyi"),
                            ("ABIA", "Abia"),
                        ],
                        help_text="State in South-East Nigeria",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Street address of the branch outlet"
                    ),
                ),
                (
                    "is_pilot_intervention",
                    models.BooleanField(
                        default=False,
                        help_text="True = Treatment branch (utilizing AI waste reduction intervention), False = Control branch",
                    ),
                ),
                (
                    "has_standby_generator",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the branch possesses a functional backup power generator",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this branch is currently open and operating",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chain",
                    models.ForeignKey(
                        help_text="Parent QSR brand",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="organization.restaurantchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["chain", "name"],
                "unique_together": {("chain", "name")},
            },
        ),
    ]
