# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(help_text="Calendar date of sale transactions"),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning_lunch", "Morning / Lunch (8AM-3PM)"),
                            ("evening_dinner", "Evening / Dinner (3PM-10PM)"),
                            ("full_day", "Full Day"),
                        ],
                        help_text="Operational shift window (Morning/Lunch, Evening/Dinner, Full Day)",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        help_text="Total item portion count sold during this shift"
                    ),
                ),
                (
                    "total_revenue_naira",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gross revenue earned in Nigerian Naira (₦)",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet where transactions occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_records",
                        to="organization.branch",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Finished dish or beverage sold",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_records",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Record",
                "verbose_name_plural": "Sales Records",
                "ordering": ["-sale_date"],
                "unique_together": {("branch", "menu_item", "sale_date", "shift")},
            },
        ),
    ]
