# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ingredient name, e.g. 'Parboiled Rice', 'Fresh Whole Chicken', 'Vegetable Oil'",
                        max_length=100,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("gram", "gram"),
                            ("litre", "litre"),
                            ("piece", "piece"),
                        ],
                        help_text="Standard unit of measure for inventory and recipe portions",
                        max_length=10,
                    ),
                ),
                (
                    "unit_cost_naira",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current cost per unit in Nigerian Naira (₦)",
                        max_digits=10,
                    ),
                ),
                (
                    "shelf_life_days_chilled",
                    models.PositiveIntegerField(
                        help_text="Days usable under refrigeration"
                    ),
                ),
                (
                    "shelf_life_days_ambient",
                    models.PositiveIntegerField(
                        help_text="Days usable at room temperature"
                    ),
                ),
                (
                    "minimum_reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Threshold quantity to trigger stock replenishment",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this ingredient is currently in active operational use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chain",
                    models.ForeignKey(
                        help_text="The restaurant chain owning this ingredient specification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="organization.restaurantchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "ordering": ["name"],
                "unique_together": {("chain", "name")},
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Menu item name, e.g. 'Jollof Rice Standard', 'Fried Chicken 1-Piece'",
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main_rice", "Main Rice"),
                            ("protein", "Protein"),
                            ("sides", "Sides"),
                            ("swallow_soup", "Swallow & Soup"),
                            ("pasta", "Pasta"),
                            ("beverage", "Beverage"),
                            ("snack", "Snack"),
                        ],
                        help_text="Menu category for operational classification",
                        max_length=30,
                    ),
                ),
                (
                    "selling_price_naira",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Retail price to customers in Nigerian Naira (₦)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_perishable_daily",
                    models.BooleanField(
                        default=True,
                        help_text="Must unsold cooked food be discarded at closing?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this menu item is currently offered",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chain",
                    models.ForeignKey(
                        help_text="The restaurant chain offering this menu item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="organization.restaurantchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "ordering": ["name"],
                "unique_together": {("chain", "name")},
            },
        ),
        migrations.CreateModel(
            name="RecipeBOM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Qty of ingredient per 1 portion",
                        max_digits=10,
                    ),
                ),
                (
                    "prep_yield_loss_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Normal cooking/prep shrinkage %",
                        max_digits=5,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        help_text="Raw ingredient constituent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_recipes",
                        to="menu.ingredient",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Finished menu item dish",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Bill of Materials",
                "verbose_name_plural": "Recipe Bills of Materials",
                "ordering": ["menu_item", "ingredient"],
                "unique_together": {("menu_item", "ingredient")},
            },
        ),
    ]
