# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("kitchen_cook", "Kitchen Cook"),
                            ("store_keeper", "Store Keeper"),
                            ("branch_manager", "Branch Manager"),
                            ("area_manager", "Area Manager"),
                            ("research_auditor", "Research Auditor"),
                            ("admin", "Admin"),
                        ],
                        default="kitchen_cook",
                        help_text="Role within the restaurant hierarchy or research framework",
                        max_length=30,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Contact telephone number for kitchen alerts / shift coordination",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned physical restaurant branch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="organization.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Underlying Django auth user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["user__username"],
            },
        ),
    ]
