# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "forecast_target_date",
                    models.DateField(help_text="The date this forecast predicts for"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the forecasting engine executed",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial_fallback", "Partial (Single Model Fallback)"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        help_text="Operational status of this predictive run",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="System logs, error traces, or operational notes",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet for which the forecast was computed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_runs",
                        to="organization.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Run",
                "verbose_name_plural": "Forecast Runs",
                "ordering": ["-executed_at"],
                "unique_together": {("branch", "forecast_target_date")},
            },
        ),
        migrations.CreateModel(
            name="DailyForecastItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chronos_prediction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Portions predicted by Amazon Chronos-Bolt",
                        max_digits=10,
                    ),
                ),
                (
                    "timesfm_prediction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Portions predicted by Google TimesFM",
                        max_digits=10,
                    ),
                ),
                (
                    "ensemble_prediction",
                    models.DecimalField(
                        decimal_places=2, help_text="Blended forecast", max_digits=10
                    ),
                ),
                (
                    "disagreement_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Absolute divergence between models",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[("high", "High"), ("low", "Low")],
                        help_text="High agreement (<8% divergence) vs Low agreement",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_prep_strategy",
                    models.CharField(
                        choices=[
                            ("single_bulk_batch", "Single Bulk Batch"),
                            ("two_staggered_batches", "Two Staggered Batches"),
                            ("three_batches", "Three Batches"),
                        ],
                        help_text="Dynamic kitchen batching strategy to avert overproduction waste",
                        max_length=30,
                    ),
                ),
                (
                    "batch_1_portions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Portions allocated to initial morning/lunch prep batch",
                    ),
                ),
                (
                    "batch_2_portions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Portions reserved for top-up afternoon batch if demand manifests",
                    ),
                ),
                (
                    "batch_3_portions",
                    models.PositiveIntegerField(
                        default=0, help_text="Portions reserved for tertiary batch"
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Target finished dish being predicted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_items",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "forecast_run",
                    models.ForeignKey(
                        help_text="Associated daily forecasting execution",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_items",
                        to="forecasting.forecastrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Forecast Item",
                "verbose_name_plural": "Daily Forecast Items",
                "ordering": ["menu_item__name"],
                "unique_together": {("forecast_run", "menu_item")},
            },
        ),
        migrations.CreateModel(
            name="KitchenPrepTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_raw_qty_to_prep",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Total raw ingredient quantity calculated via Recipe BOM",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_used_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Filled by cook at end of shift",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "variance_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Difference: recommended vs actual",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "forecast_run",
                    models.ForeignKey(
                        help_text="Associated forecast run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_targets",
                        to="forecasting.forecastrun",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        help_text="Raw ingredient constituent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prep_targets",
                        to="menu.ingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitchen Prep Target",
                "verbose_name_plural": "Kitchen Prep Targets",
                "ordering": ["ingredient__name"],
                "unique_together": {("forecast_run", "ingredient")},
            },
        ),
    ]
