# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("menu", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operational_stage",
                    models.CharField(
                        choices=[
                            ("preparation", "Preparation & Cooking"),
                            ("storage_spoilage", "Storage & Spoilage"),
                            ("overproduction_buffet", "Overproduction & Buffet"),
                            ("plate_waste", "Customer Plate Waste"),
                        ],
                        help_text="Stage in restaurant lifecycle where waste was generated",
                        max_length=30,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Measured weight of discarded food in kilograms",
                        max_digits=10,
                    ),
                ),
                (
                    "financial_loss_naira",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-calculated from weight and unit cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "root_cause_determinant",
                    models.CharField(
                        choices=[
                            ("power_outage_spoilage", "Power Outage / Spoilage"),
                            ("overcooked_burnt", "Overcooked / Burnt"),
                            ("expired_in_store", "Expired in Storage"),
                            ("overproduced_unsold", "Overproduced / Unsold"),
                            ("customer_leftover", "Customer Leftover"),
                            ("trimming_excess", "Trimming / Peeling Excess"),
                            ("other", "Other"),
                        ],
                        help_text="Primary driver or trigger for waste event",
                        max_length=30,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional context or remarks"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet where waste occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_logs",
                        to="organization.branch",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        help_text="If discarded item was a raw ingredient",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_logs",
                        to="menu.ingredient",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member logging the waste entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_logs",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="If discarded item was a cooked dish",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_logs",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Log",
                "verbose_name_plural": "Waste Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
