# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total quantity received upon delivery",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current remaining quantity available for cooking",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_cost_at_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit paid at time of purchase in Naira (₦)",
                        max_digits=10,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        help_text="Date this batch was delivered and received"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Expiration date calculated from shelf life and storage conditions"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("chilled", "Chilled"),
                            ("ambient", "Ambient"),
                            ("frozen", "Frozen"),
                        ],
                        help_text="Storage method (chilled, ambient, frozen)",
                        max_length=20,
                    ),
                ),
                (
                    "is_depleted",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating whether batch has been fully consumed or discarded",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes regarding batch quality, supplier, or delivery condition",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet holding this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_batches",
                        to="organization.branch",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        help_text="Ingredient type for this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_batches",
                        to="menu.ingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Batch",
                "verbose_name_plural": "Inventory Batches",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="PowerOutageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outage_start",
                    models.DateTimeField(
                        help_text="Timestamp when power failure began"
                    ),
                ),
                (
                    "outage_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when power was restored (grid or generator)",
                        null=True,
                    ),
                ),
                (
                    "generator_available",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a standby generator was operational during the outage",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Details on chiller temperatures, food safety checks, or fuel shortages",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet experiencing the outage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_outage_logs",
                        to="organization.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Power Outage Log",
                "verbose_name_plural": "Power Outage Logs",
                "ordering": ["-outage_start"],
            },
        ),
    ]
