# Generated by Django 5.1.15 on 2026-09-24 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalCalendarContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Calendar date")),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("ENUGU", "Enugu"),
                            ("AWKA", "Awka"),
                            ("OWERRI", "Owerri"),
                            ("ABAKALIKI", "Abakaliki"),
                            ("UMUAHIA", "Umuahia"),
                            ("ONITSHA", "Onitsha"),
                            ("ABA", "Aba"),
                        ],
                        help_text="Target urban center in South-East Nigeria",
                        max_length=50,
                    ),
                ),
                (
                    "traditional_market_day",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("eke", "Eke"),
                            ("oye", "Oye"),
                            ("afor", "Afor"),
                            ("nkwo", "Nkwo"),
                        ],
                        default="none",
                        help_text="Igbo traditional 4-day market name (Eke, Oye, Afor, Nkwo)",
                        max_length=10,
                    ),
                ),
                (
                    "is_major_market_day",
                    models.BooleanField(
                        default=False,
                        help_text="True if this market day is significant for this particular city",
                    ),
                ),
                (
                    "is_payday_window",
                    models.BooleanField(
                        default=False,
                        help_text="True if date falls within civil service/corporate salary window (25th-31st)",
                    ),
                ),
                (
                    "is_sunday_church_surge",
                    models.BooleanField(
                        default=False,
                        help_text="True if date falls on a Sunday with heightened post-service restaurant dining",
                    ),
                ),
                (
                    "is_public_holiday",
                    models.BooleanField(
                        default=False,
                        help_text="True if date is a recognized national or state public holiday",
                    ),
                ),
                (
                    "public_holiday_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of observed holiday, e.g. Workers Day, Christmas Day",
                        max_length=100,
                    ),
                ),
                (
                    "weather_flag",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("rainy_afternoon", "Rainy Afternoon"),
                            ("heavy_downpour", "Heavy Downpour"),
                            ("harmattan", "Harmattan"),
                        ],
                        default="sunny",
                        help_text="Expected or recorded prevailing weather condition",
                        max_length=20,
                    ),
                ),
                (
                    "custom_event_note",
                    models.TextField(
                        blank=True,
                        help_text="E.g. University graduation week, local festival, gubernatorial election",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Local Calendar Context",
                "verbose_name_plural": "Local Calendar Contexts",
                "ordering": ["-date"],
                "unique_together": {("date", "city")},
            },
        ),
    ]
