# Generated by Django 5.1.15 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuEngineeringSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start date of the observation period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of the observation period"),
                ),
                (
                    "units_sold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total customer portions sold during period",
                    ),
                ),
                (
                    "waste_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Total waste mass discarded in kilograms",
                        max_digits=10,
                    ),
                ),
                (
                    "waste_cost_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Financial value lost to food waste in Nigerian Naira (₦)",
                        max_digits=12,
                    ),
                ),
                (
                    "revenue_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross sales revenue earned in Nigerian Naira (₦)",
                        max_digits=12,
                    ),
                ),
                (
                    "ingredient_cost_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total raw ingredient cost calculated from Recipe BOM",
                        max_digits=12,
                    ),
                ),
                (
                    "profit_margin_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross margin: revenue - ingredient cost",
                        max_digits=12,
                    ),
                ),
                (
                    "matrix_category",
                    models.CharField(
                        choices=[
                            ("star", "Star (High Profit, Low Waste)"),
                            ("plowhorse", "Plowhorse (High Sales, Low Profit)"),
                            ("puzzle", "Puzzle (Low Sales, High Profit)"),
                            ("dog", "Dog (Low Sales, Low Profit, High Waste)"),
                        ],
                        help_text="Menu engineering quadrant classification",
                        max_length=15,
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        blank=True,
                        help_text="Prescriptive operational recommendation for kitchen and management",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Snapshot generation timestamp"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet where analysis was evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_snapshots",
                        to="organization.branch",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Menu dish evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_snapshots",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Engineering Snapshot",
                "verbose_name_plural": "Menu Engineering Snapshots",
                "ordering": ["-period_end"],
                "unique_together": {
                    ("branch", "menu_item", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="PilotKPISnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(help_text="Date this KPI snapshot summarizes"),
                ),
                (
                    "period_label",
                    models.CharField(
                        choices=[
                            ("pre_intervention", "Pre-Intervention"),
                            ("post_intervention", "Post-Intervention"),
                        ],
                        help_text="Research trial phase: baseline pre-intervention vs AI post-intervention",
                        max_length=20,
                    ),
                ),
                (
                    "total_waste_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Total aggregate food waste generated in kilograms",
                        max_digits=10,
                    ),
                ),
                (
                    "total_waste_cost_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total monetary loss from discarded food in Nigerian Naira (₦)",
                        max_digits=12,
                    ),
                ),
                (
                    "total_sales_revenue_naira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total sales revenue in Nigerian Naira (₦)",
                        max_digits=12,
                    ),
                ),
                (
                    "waste_to_revenue_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="waste_cost / revenue ratio",
                        max_digits=5,
                    ),
                ),
                (
                    "forecast_accuracy_mape",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean Absolute Percentage Error of forecast",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when snapshot record was logged",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch outlet evaluated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilot_kpis",
                        to="organization.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilot KPI Snapshot",
                "verbose_name_plural": "Pilot KPI Snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("branch", "snapshot_date", "period_label")},
            },
        ),
    ]
